Story9/urls.py
from django.urls import path

from . import views

app_name = 'Story9'

urlpatterns = [
    path('Story9/', views.home, name ='home'),
    path('Story9/signup/', views.signup, name='signup'),
    path('Story9/login/', views.signin, name='login'),
    path('Story9/logout/', views.signout, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.story1, name='story1'),
    path('home', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('contact', views.contact, name='contact'),
    path('experience', views.experience, name='experience'),
    path('matkuls', views.matkuls, name='matkuls'),
    path('hasil', views.hasil, name='hasil'),
    path('hapus/<str:pk>/', views.hapus, name='hapus'),
    path('tambahkegiatan', views.tambahkegiatan, name='tambahkegiatan'),
    path('daftarkegiatan', views.daftarkegiatan, name='daftarkegiatan'),
    path('hapuskegiatan/<str:pk>/', views.hapuskegiatan, name='hapuskegiatan'),
    path('tambahnama/<int:id>', views.tambahnama, name='tambahnama'),
    path('hapusnama/<str:pk>/', views.hapusnama, name='hapusnama'),
    path('story7', views.story7, name='story7'),
    path('story8', views.story8, name='story8'),
    path('data/', views.data, name='data'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('Story9.urls',namespace="Story9")),
]

Story9/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class matkul(models.Model):
    nama = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=30)
    deskripsi = models.CharField(max_length=30)
    tahun = models.CharField(max_length=30)
    kelas = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class tambah(models.Model):
    namakegiatan = models.CharField(max_length=30)

    def listPeserta(self):
        return pendaftar.objects.filter(kegiatan=self.id)

    peserta = property(listPeserta)

    def __str__(self):
        return self.namakegiatan

class pendaftar(models.Model):
    kegiatan = models.ForeignKey(tambah, null=True,on_delete=models.CASCADE)
    namapendaftar = models.CharField(max_length=30)

    def __str__(self):
        return self.namapendaftar

# Create your models here.

main/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from django.forms import widgets
from .models import matkul, pendaftar,tambah

class tambahkan(ModelForm):
    class Meta:
        model = matkul;
        fields = '__all__'
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'dosen' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.TextInput(attrs={'class': 'form-control'}),
            'deskripsi' : forms.TextInput(attrs={'class': 'form-control'}),
            'tahun' : forms.TextInput(attrs={'class': 'form-control'}),
            'kelas' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class tambahkankegiatan(ModelForm):
    class Meta:
        model = tambah;
        fields = '__all__'
        widgets = {
            'namakegiatan' : forms.TextInput(attrs={'class': 'form-control'}),
        }

class tambahkannama(ModelForm):
    class Meta:
        model = pendaftar;
        fields = '__all__'
        widgets = {
            'namapendaftar' : forms.TextInput(attrs={'class': 'form-control'}),
        }

Story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

# Create your views here.

def home(request):
    return render(request, 'Story9.html')
    
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
 
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            return redirect('/Story9/login')
         
        else:
            return render(request,'signup.html',{'form':form})
     
    else:
        form = UserCreationForm()
        return render(request,'signup.html',{'form':form})

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
 
        if user is not None:
            login(request,user)
            return redirect('/Story9')
        else:
            form = AuthenticationForm()
            messages.error(request, 'Username atau password Anda salah')
            return render(request,'login.html',{'form':form})
     
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form':form})

def signout(request):
    logout(request)
    return redirect('/Story9/')

main/views.py
from django.shortcuts import render, redirect
from .models import pendaftar, matkul, tambah
from .forms import tambahkan, tambahkankegiatan, tambahkannama
from django.http.response import JsonResponse
from pip._vendor import requests
import json

def home(request):
    return render(request, 'main/home.html')
def story1(request):
    return render(request, 'main/story1.html')
def profile(request):
    return render(request, 'main/profile.html')
def contact(request):
    return render(request, 'main/contact.html')
def experience(request):
    return render(request, 'main/experience.html')
def matkuls(request):
    form = tambahkan()
    context = {'form':form}
    if request.method == 'POST':
        form = tambahkan(request.POST)
        form_class = tambahkan
        if form.is_valid():
            form.save()
            return redirect('/hasil')
    return render(request, 'main/matkul.html',context)
def hasil(request):
    result = matkul.objects.all()
    context = {'result':result}
    return render(request, 'main/hasil.html',context)
def hapus(request,pk):
    hapus = matkul.objects.get(id=pk)
    hapus.delete()
    return redirect('/hasil')

def tambahkegiatan(request):
    form = tambahkankegiatan()
    context = {'form':form}
    if request.method == 'POST':
        form = tambahkankegiatan(request.POST)
        form_class = tambahkankegiatan
        if form.is_valid():
            post = form.save(commit=True)
            post.save()
            return redirect('/daftarkegiatan')
    return render(request, 'main/tambahkegiatan.html',context)
def daftarkegiatan(request):
    result = tambah.objects.all()
    context = {'result':result}
    return render(request, 'main/daftarkegiatan.html',context)

def hapuskegiatan(request,pk):
    hapus = tambah.objects.get(id=pk)
    hapus.delete()
    return redirect('/daftarkegiatan')

def tambahnama(request,id):
    daftar = tambah.objects.get(id=id)
    forms = tambahkannama(request.POST, instance=daftar)
    if forms.is_valid():
        data = pendaftar()
        data.kegiatan = forms.cleaned_data['kegiatan']
        data.namapendaftar = forms.cleaned_data['namapendaftar']
        data.save()
        return redirect('/daftarkegiatan')
    context = {'forms':forms, 'daftar':daftar}
    return render(request, 'main/tambahnama.html',context)

def hapusnama(request,pk):
    hapus = pendaftar.objects.get(id=pk)
    hapus.delete()
    return redirect('/daftarkegiatan')

def story7(request):
    return render(request, 'main/story7.html')

def story8(request):
    response = {}
    return render(request, 'main/story8.html', response)

def data(request):
    url="https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret=requests.get(url)

    data=json.loads(ret.content)
    return JsonResponse(data,safe=False)

Story9/templates/Story9.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% endblock meta %}

{% block content %}
<div class="navigation">
    <ul class="nav justify-content-start">
        {% if user.is_authenticated %}
            <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Hi, {{ user.get_username }}</a>
            <a class="nav-link" href="{% url 'Story9:logout' %}"><img src="https://icon-library.com/images/logout-icon-png/logout-icon-png-3.jpg" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Logout</a>
        {% else %}
            <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Hi, Guest</a>
            <a class="nav-link" href="{% url 'Story9:login' %}"><img src="https://icon-library.com/images/11a7acda9d.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Login</a>
        {% endif %}
    </ul>
</div>

<div class="banner">
    <div class="bann">
        {% if user.is_authenticated %}
            <h1>Selamat Datang, {{ user.get_username }} !</h1>
        {% else %}
            <h1>Selamat Datang!</h1>
        {% endif %}
    </div>
</div>


{% endblock content %}

Story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log In</title>
{% endblock meta %}

{% block content %}
<div class="signin">
    <form id="signin" method='POST'>
        <h2>Log In</h2><br>
        {% csrf_token %}
        {{form.as_p}}
        <br><br>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
                <br><br>
            {% endif %}
        {% endfor %}

        <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type = "submit" value = "Log in">
        <br><br>
        <p>Belum punya akun ? Sign up dulu di <a class="sinisignup" href = "{% url 'Story9:signup' %}">sini</a></p><br>
    </form>
</div>
{% endblock content %}

Story9/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign Up</title>
{% endblock meta %}

{% block content %}
<div class="signup">
    <form id="signup" method='POST'>
        <h2>Sign Up</h2><br>
        {% csrf_token %}
        {% for field in form %}
            <p>
            {{ field.label_tag }}<br>
            <p class="inputan">{{ field }}</p>
            {% for error in field.errors %}
                <p style="color: rgb(179, 0, 0)">{{ error }}</p>
            {% endfor %}
            </p>
        {% endfor %}
        <br>
        <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type="submit" value = "Sign up">
        <br><br>
        <p>Sudah punya akun? Langsung log in di <a class="sinilogin" href="{% url 'Story9:login' %}">sini</a></p>
    </form>
    
</div>
{% endblock content %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>contact</title>
{% endblock meta %}

{% block content %}    
    <div class="container">
        <div class="row align-items-center mx-auto mt-5">
            <div class="col">
                <img src="{% static 'img/line.png' %}" alt="line logo">
            </div>
            <div class="col">
                <img src="{% static 'img/wa.png' %}" alt="wa logo">
            </div>
        </div>
        
    </div>
    <div class="container">
        <div class="row align-items-center mx-auto mt-5">
            <div class="col">
                <h3>fadhl27(ID line)</h3>
            </div>
            <div class="col">
                <h3>0895639335729</h3>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/daftarkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>daftar kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="row">
    {% for res in result %}
		<div class="col mb-5">
			<div class="card" style="width: 18rem;">
				<div class="card-header">
					<div class="text-center">
						{{res.namakegiatan}}
					</div>
				</div>
					{% for r in res.peserta %}		
						<a>{{r.namapendaftar}}</a>			
					{% endfor %}
				<a type="button" class="btn btn-dark" href={%url 'main:tambahnama' res.id%}>tambah nama</a>
				<a type="button" class="btn btn-dark" href={%url 'main:hapuskegiatan' res.id%}>hapus kegiatan</a>
			</div>
		</div>    
	{% endfor %}
    
  </div>
</div>	
<div class="text-center">			
	<a type="button" class="btn btn-dark" href={%url 'main:tambahkegiatan'%}>tambah kegiatan</a>
</div>
{% endblock content %}


      

main/templates/main/experience.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>experience</title>
{% endblock meta %}

{% block content %}
    <div class="container">
        <div class="row align-items-center mx-auto mt-5">
            <div class="col">
                <img src="{% static 'img/fuki.png' %}" alt="fuki logo">
            </div>
            <div class="col">
                <img src="{% static 'img/mediafuki.png' %}" alt="fuki media logo">
            </div>
        </div>
        
    </div>
    <div class="container">
        <div class="row align-items-center mx-auto mt-5">
            <div class="col">
                <h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;staff at media fuki fasilkom ui</h1>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/hasil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>hasil</title>
{% endblock meta %}

{% block content %}
<form method="POST">
<table class="table table-striped">
    <tr>
		<th>nama</th>
		<th>Dosen</th>
		<th>sks</th>
		<th>deskripsi</th>
		<th>tahun</th>
		<th>kelas</th>
        <th>hapus</th>
	</tr>

		{% for res in result %}
			<tr>
				<td>{{res.nama}}</td>
				<td>{{res.dosen}}</td>
				<td>{{res.sks}}</td>
                <td>{{res.deskripsi}}</td>
				<td>{{res.tahun}}</td>
				<td>{{res.kelas}}</td>
                
                <td><a type="button" class="btn btn-dark" href={%url 'main:hapus' res.id%}>hapus</a></td>
			</tr>    
		{% endfor %}
</table>
<div class="text-center">
    <a type="button" class="btn btn-dark" href={%url 'main:matkuls'%}>tambah</a>
</div>
</form>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>home</title>
<style>
  body{
    background-color: black;
  }
</style>
{% endblock meta %}

{% block content %}
<img src="{% static 'img/gambar.jpg' %}" class="rounded-circle mx-auto d-block mt-5" width=400 height=350 alt="foto saya">
<div class="container">
  <div class="row">
    <div class="btn btn-light btn-lg mx-auto mt-5">
      <a href="{% url 'main:profile' %}" role="button" style="color: black; text-decoration: none;">	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;See My Profile	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;</a>
      <a href="{% url 'main:story1' %}" role="button" style="color: black; text-decoration: none;">	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;Story1	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;	&nbsp;</a>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>matkul</title>
{% endblock meta %}

{% block content %}
<form method="POST">
<div class="form-group">
    {% csrf_token %}
    {{form.as_p}}
</div>
    <input type="submit" class="btn btn-dark" value="tambah">
</form>
{% endblock content %}

main/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>profile</title>
{% endblock meta %}
    
{% block content %}
    <div class="container">
        <div class="row align-items-center">
          <div class="col-md-auto">
            <img src="{% static 'img/gambar-removebg-preview.png' %}" alt="foto saya 2" width = "500" height="700">
          </div>
          <div class="col">
            <h1>Fadhl</h1>
            <p>Mahasiswa Sistem Informasi di Fakultas <br>
            Ilmu Komputer Universitas Indonesia</p>
            <h3>NPM</h3>
            <p>1906353952</p>
            <h3>hobi</h3>
            <p>Sepakbola</p>
            <h3>riwayat pendidikan</h3>
            <p>SD islam Al-Azhar 1 <br>
            SMP islam Al-Azhar 1<br>
            SMA islam Al-Azhar 1</p>
          </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story1</title>
{% endblock meta %}
{% block content %}
    <h1>profil saya</h1>
    <img src="{% static 'img/gambar.jpg' %}" alt="foto saya">
    <p>nama: fadhl</p>
    <p>npm: 1906353952</p>
    <p>angkatan: 2019</p>
    <p>hobi: sepakbola</p>
    <p>deskripsi diri: rajin belajar</p>
    <p>tempat kuliah: Universitas Indonesia</p>
    <p>riwayat pendidikan: SMA al-azhar 1</p>
    <p>media sosial: fadhl27 (ID line)</p>
    <a href="{% url 'main:home' %}" role="button"> Story3</a>
{% endblock content %}

main/templates/main/story7.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>story7</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}

{% block content %}
<!--<button id="swap">swap</button>-->
<div class="card" id="acc1">
<h3 class="accordion" >aktivitas saat ini<button class="btn btn-dark" id="turun1" style="float: right">turun</button><button class="btn btn-dark" id="naik1" style="float: right">naik</button></h3>
<div class="panel">
  <p>mahasiswa s1 di fakultass ilmu komputer universitas indonesia</p>
</div>
</div>

<div class="card" id="acc2">
<h3 class="accordion" >pengalaman organisasi/kepanitiaan<button class="btn btn-dark" id="turun2" style="float: right">turun</button><button class="btn btn-dark" id="naik2" style="float: right">naik</button></h3>
<div class="panel">
  <p>staff bagian media di fuki fasilkom ui</p>
</div>
</div>

<div class="card" id="acc3">
<h3 class="accordion">prestasi<button class="btn btn-dark" id="turun3" style="float: right">turun</button><button class="btn btn-dark" id="naik3" style="float: right">naik</button></h3>
<div class="panel">
  <p>piala dunia 2022</p>
</div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}


$("#naik1").click(function(){
  var target = $("#acc1").prev();
  if (target.is(".card")) {
    $("#acc1").after(target);
  }
});

$("#naik2").click(function(){
  var target = $("#acc2").prev();
  if (target.is(".card")) {
    $("#acc2").after(target);
  }
});

$("#naik3").click(function(){
  var target = $("#acc3").prev();
  if (target.is(".card")) {
    $("#acc3").after(target);
  }
});

$("#turun1").click(function(){
  var target = $("#acc1").next();
  if (target.is(".card")) {
    $("#acc1").before(target);
  }
});

$("#turun2").click(function(){
  var target = $("#acc2").next();
  if (target.is(".card")) {
    $("#acc2").before(target);
  }
});

$("#turun3").click(function(){
  var target = $("#acc3").next();
  if (target.is(".card")) {
    $("#acc3").before(target);
  }
});
</script>
</script>
{% endblock content %}

main/templates/main/story8.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story8</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}

{% block content %}
    <input id="keyword" class="form-control mt-3" placeholder="judul buku">

    <table id="daftar_buku" class="table table-bordered mt-3">
    </table>

<script type="text/javascript">
    $("#keyword").keyup(function(){
        var inp = $("#keyword").val();
        $.ajax({
            url: '/data/?q='+inp,
            success:function(data) {
                var array_items = data.items;
                $("#daftar_buku").empty();
                $("#daftar_buku").append("<thead class=\"thead-light\"><br><tr><br><th scope=\"col\">No</th><br><th scope=\"col\">Judul</th><br><th scope=\"col\">Gambar</th><br></thead>");
                for (i = 0; i<array_items.length; i++) {
                    var judul = array_items[i].volumeInfo.title;
                    var gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
                    $("#daftar_buku").append("<tbody><br><tr><br><th scope=\"row\">"+(i+1)+"</th><br><td>"+judul+"</td><br><td><img src="+gambar+"></td><br></tr><br></tbody>");
                }
            }
        });
    });
</script>
{% endblock content %}

main/templates/main/tambahkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>tambahkegiatan</title>
{% endblock meta %}

{% block content %}
<form method="POST">
<div>
    {% csrf_token %}
    {{form.as_p}}
</div>
    <input type="submit" class="btn btn-dark" value="tambah">
</form>
{% endblock content %}

main/templates/main/tambahnama.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>tambah nama</title>
{% endblock meta %}

{% block content %}
<form method="POST">
<div class="form-group">
    {% csrf_token %}
    {{forms.as_p}}
</div>
    <input type="submit" class="btn btn-dark" value="tambah nama">
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>

  <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
      <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="collapse_target">
      <span class="navbar-brand" href="{% url 'main:home' %}">STORY PPW</span>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:profile' %}">profile <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:contact' %}">contact <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:experience' %}">experience <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:matkuls' %}">matkul <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:hasil' %}">hasil <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:tambahkegiatan' %}">tambah kegiatan <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:daftarkegiatan' %}">daftar kegiatan <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story7' %}">story7 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:story8' %}">story8 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Story9:home' %}">story9 <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      </div>
  </nav>
  
  {% block content %}
  {% endblock content %}
</html>